/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      link: {
        type: 'generated-index',
        title: 'Portkey Guides',
        description: 'Learn about the most important Docusaurus concepts!',
        slug: '/docs/portkey-guides',
        keywords: ['portkey-guides'],
        image: '/img/docusaurus.png',
      },
      label: 'overview of portkey',
      items: [
        {
          type: 'doc',
          id: 'OverviewOfPortkey/start-here',
        },
        {
          type: 'doc',
          id: 'OverviewOfPortkey/what-is-portkey',
        },
        {
          type: 'doc',
          id: 'OverviewOfPortkey/agency',
        },
        {
          type: 'doc',
          id: 'OverviewOfPortkey/Security',
        },
      ],
    },
    {
      type: 'category',
      label: 'quickStartGuides',
      items: [
        {
          type: 'category',
          label: 'ProviderGuides',
          items: [
            {
              type: 'doc',
              id: 'quickStartGuides/ProviderGuides/ProviderGuides',
            },
          ]
        },
        {
          type: 'category',
          label: 'basicGuidesForSDKs',
          items: [
            {
              type: 'doc',
              id: 'quickStartGuides/basicGuidesForSDKs/basicGuidesForSDKs',
            },
          ]
        },
        {
          type: 'category',
          label: 'tokenGuides',
          items: [{
            type: 'doc',
            id: 'quickStartGuides/tokenGuides/tokenGuides'
          }]
        },
      ],
    },
    {
      type: 'category',
      label: 'SDKs',
      items: [
        {
          type: 'category',
          label: 'coreSDK',
          items: [
            {
              type: 'doc',
              id: 'SDKs/coreSDK/coreSDK'
            }
          ]
        },
        {
          type: 'category',
          label: 'UISDK',
          items: [
            {
              type: 'doc',
              id: 'SDKs/UISDK/UISDK'
            }
          ]
        },
      ],
    },
    {
      type: 'category',
      label: 'APIReferences',
      items: [
        {
          type: 'doc',
          id: 'APIReferences/GraphQL'
        },
        {
          type: 'doc',
          id: 'APIReferences/RESTful'
        },
        {
          type: 'doc',
          id: 'APIReferences/contract'
        },
      ],
    },
    'environmentalConfiguration',
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [
        {
          type: 'doc',
          id: 'Troubleshooting/FAQ'
        }
      ],
    },
  ]
};

module.exports = sidebars;
